Settings = {
    movement_modes = {
        disabled = 1,
        match_yaw = 2,
        reverse_angle = 3,
        match_angle = 4,
    },
    swimming_button = "A",
    controller_index = 1,
    goal_angle = 0,
    goal_mag = 127,
    override_rng = false,
    override_rng_use_index = false,
    override_rng_value = 0,
    show_effective_angles = true,
    ghost_path = folder .. "recording.ghost",
    strain_left = true,
    strain_right = false,
    dyaw = false,
    strain_speed_target = false,
    strain_always = false,
    high_magnitude = false,
    atan_strain = false,
    swim = false,
    grid_size = 35,
    grid_gap = 2,
    movement_mode = 1,
    track_moved_distance = false,
    moved_distance_ignore_y = false,
    moved_distance = 0,
    moved_distance_axis = {
        x = 0,
        y = 0,
        z = 0
    },
    reverse_arc = false,
    atan_start = 0,
    atan_r = 1.0,
    atan_d = 0.0,
    atan_n = 10,
    atan_exp = 0,
    framewalk = false,
    grind = false,
    grind_divisor = 8,
    grind_left = true,
    styles = {
        dofile(res_path .. "windows-11.lua"),
        dofile(res_path .. "windows-10.lua"),
        dofile(res_path .. "windows-10-dark.lua"),
        dofile(res_path .. "windows-7.lua"),
        dofile(res_path .. "windows-3-pink.lua"),
        dofile(res_path .. "crackhex.lua"),
        dofile(res_path .. "fl-studio.lua"),
    },
    active_style_index = 1
}

Mupen_lua_ugui_ext.apply_nineslice(Settings.styles[Settings.active_style_index].theme)